using System;

namespace Actemium.History.Model
{

	/// <summary>
	/// Object model class for HistoryKeys
	/// </summary>
	[Serializable]
	public partial class HistoryKey : HistoryKeyGennie
  {
		private const string CLASSNAME = nameof(HistoryKey);

		public HistoryKey() : base() { }

		public HistoryKey(String historyKey, Boolean showInClient, Boolean saveInDatabase, String traceLevel)
			: base(historyKey, showInClient, saveInDatabase, traceLevel)
		{

		}
  }


	/// <summary>
	/// Object model class for HistoryKeysGennie (Generated by Gennie)
	/// </summary>
	[Serializable]
	public abstract class HistoryKeyGennie
	{
		private const string CLASSNAME = nameof(HistoryKeyGennie);


		/// <summary>
		/// Default constructor
		/// </summary>
		protected HistoryKeyGennie()
		{
		    //Empty constructor
		}


		/// <summary>
		/// Constructor with all parameters
		/// </summary>
		protected HistoryKeyGennie(String historyKey, Boolean showInClient, Boolean saveInDatabase, String traceLevel)
		{
			_historyKey = historyKey;
			_showInClient = showInClient;
			_saveInDatabase = saveInDatabase;
			_traceLevel = traceLevel;
		}


		/// <summary>
		/// Property: HistoryKey
		/// </summary>
    public String HistoryKey
		{
			set { _historyKey = value; }
			get { return _historyKey; }
		} protected String _historyKey;


		/// <summary>
		/// Property: ShowInClient
		/// </summary>
    public Boolean ShowInClient
		{
			set { _showInClient = value; }
			get { return _showInClient; }
		} protected Boolean _showInClient;


		/// <summary>
		/// Property: SaveInDatabase
		/// </summary>
    public Boolean SaveInDatabase
		{
			set { _saveInDatabase = value; }
			get { return _saveInDatabase; }
		} protected Boolean _saveInDatabase;


		/// <summary>
		/// Property: TraceLevel
		/// Description: System.Diagnostics.SourceLevels excluding ActivityTracing and All
		/// </summary>
    public String TraceLevel
		{
			set { _traceLevel = value; }
			get { return _traceLevel; }
		} protected String _traceLevel;


    /// <summary>
		/// Override the default ToString function to show all properties of the class
		/// </summary>
    public override string ToString()
    {
      return string.Format("HistoryKey:HistoryKey={0}, ShowInClient={1}, SaveInDatabase={2}, TraceLevel={3}", 
			_historyKey, _showInClient, _saveInDatabase, _traceLevel);
    }
    
    
		/// <summary>
		/// Override the default Equals function to compare class
		/// </summary>    
    public override bool Equals(object obj)
    {
      if (obj is String)
      {
        return (HistoryKey == (String)obj);
      }
      else
        if (obj is HistoryKey)
      {
        return Equals((HistoryKey)obj);
      }

      return false;

		}


		/// <summary>
		/// Equals function to compare class
		/// </summary>    
		public virtual bool Equals(HistoryKey obj)
		{
			return ((this.HistoryKey.Equals(obj.HistoryKey)));
		}


		/// <summary>
		/// Override the default GetHashCode
		/// </summary> 
		public override int GetHashCode()
		{
		  return HistoryKey.GetHashCode();
    }
		
  }
}
