using System;

namespace Actemium.L3IC.OrderManager.Model
{

	/// <summary>
	/// Object model class for MaterialParameters
	/// Description: Material specific parameters
	/// </summary>
	[Serializable]
	public partial class MaterialParameter : MaterialParameterGennie
  {
		private const string CLASSNAME = nameof(MaterialParameter);

		public MaterialParameter() : base() { }

		public MaterialParameter(Int32 id, String code, Int32 materialGroupId)
			: base(id, code, materialGroupId)
		{

		}
  }


	/// <summary>
	/// Object model class for MaterialParametersGennie (Generated by Gennie)
	/// </summary>
	[Serializable]
	public abstract class MaterialParameterGennie
	{
		private const string CLASSNAME = nameof(MaterialParameterGennie);


		/// <summary>
		/// Default constructor
		/// </summary>
		public MaterialParameterGennie()
		{
		    //Empty constructor
		}


		/// <summary>
		/// Constructor with all parameters
		/// </summary>
		public MaterialParameterGennie(Int32 id, String code, Int32 materialGroupId)
		{
			_id = id;
			_code = code;
			_materialGroupId = materialGroupId;
		}


		/// <summary>
		/// Property: Id
		/// Description: (AutoIdentity) Unique identification of the material parameter
		/// </summary>
    public Int32 Id
		{
			set { _id = value; }
			get { return _id; }
		} protected Int32 _id;


		/// <summary>
		/// Property: Code
		/// Description: Unique key of this material parameter
		/// </summary>
    public String Code
		{
			set { _code = value; }
			get { return _code; }
		} protected String _code;


		/// <summary>
		/// Property: MaterialGroupId
		/// Description: (FK to MaterialGroups) MaterialParameters are material group specific. The material group this material parameter belongs to
		/// </summary>
    public Int32 MaterialGroupId
		{
			set { _materialGroupId = value; }
			get { return _materialGroupId; }
		} protected Int32 _materialGroupId;


    /// <summary>
		/// Override the default ToString function to show all properties of the class
		/// </summary>
    public override string ToString()
    {
      return string.Format("MaterialParameter:Id={0}, Code={1}, MaterialGroupId={2}", 
			_id, _code, _materialGroupId);
    }
    
    
		/// <summary>
		/// Override the default Equals function to compare class
		/// </summary>    
    public override bool Equals(object obj)
    {
			if (obj is Int32)
			{
				return (Id == (Int32)obj);
			}
			else
				if (obj is MaterialParameter)
					return Equals((MaterialParameter)obj);
			return false;

		}


		/// <summary>
		/// Equals function to compare class
		/// </summary>    
		public virtual bool Equals(MaterialParameter obj)
		{
			return ((this.Id.Equals(((MaterialParameter)obj).Id)));
		}


		/// <summary>
		/// Override the default GetHashCode
		/// </summary> 
		public override int GetHashCode()
		{
		  int result = 0;
		  result = Id.GetHashCode();

		  return result;
		}
		
  }
}
