using System;

namespace Actemium.L3IC.OrderManager.Model
{

	/// <summary>
	/// Object model class for MaterialGroups
	/// Description: All groups of material needed for production. Both raw as finished good material groups are defined in this table
	/// </summary>
	[Serializable]
	public partial class MaterialGroup : MaterialGroupGennie
  {
		private const string CLASSNAME = nameof(MaterialGroup);

		public MaterialGroup() : base() { }

		public MaterialGroup(Int32 id, String code, String description)
			: base(id, code, description)
		{

		}
  }


	/// <summary>
	/// Object model class for MaterialGroupsGennie (Generated by Gennie)
	/// </summary>
	[Serializable]
	public abstract class MaterialGroupGennie
	{
		private const string CLASSNAME = nameof(MaterialGroupGennie);


		/// <summary>
		/// Default constructor
		/// </summary>
		public MaterialGroupGennie()
		{
		    //Empty constructor
		}


		/// <summary>
		/// Constructor with all parameters
		/// </summary>
		public MaterialGroupGennie(Int32 id, String code, String description)
		{
			_id = id;
			_code = code;
			_description = description;
		}


		/// <summary>
		/// Property: Id
		/// Description: (AutoIdentity) Unique identification of the material group
		/// </summary>
    public Int32 Id
		{
			set { _id = value; }
			get { return _id; }
		} protected Int32 _id;


		/// <summary>
		/// Property: Code
		/// Description: Unique key of this material group
		/// </summary>
    public String Code
		{
			set { _code = value; }
			get { return _code; }
		} protected String _code;


		/// <summary>
		/// Property: Description
		/// Description: Description of this material group
		/// </summary>
    public String Description
		{
			set { _description = value; }
			get { return _description; }
		} protected String _description;


    /// <summary>
		/// Override the default ToString function to show all properties of the class
		/// </summary>
    public override string ToString()
    {
      return string.Format("MaterialGroup:Id={0}, Code={1}, Description={2}", 
			_id, _code, _description);
    }
    
    
		/// <summary>
		/// Override the default Equals function to compare class
		/// </summary>    
    public override bool Equals(object obj)
    {
			if (obj is Int32)
			{
				return (Id == (Int32)obj);
			}
			else
				if (obj is MaterialGroup)
					return Equals((MaterialGroup)obj);
			return false;

		}


		/// <summary>
		/// Equals function to compare class
		/// </summary>    
		public virtual bool Equals(MaterialGroup obj)
		{
			return ((this.Id.Equals(((MaterialGroup)obj).Id)));
		}


		/// <summary>
		/// Override the default GetHashCode
		/// </summary> 
		public override int GetHashCode()
		{
		  int result = 0;
		  result = Id.GetHashCode();

		  return result;
		}
		
  }
}
