using System;

namespace Actemium.L3IC.OrderManager.Model
{

	/// <summary>
	/// Object model class for OrderMessages
	/// Description: Logging of all messages that have been received for orders from an external system
	/// </summary>
	[Serializable]
	public partial class OrderMessage : OrderMessageGennie
  {
		private const string CLASSNAME = nameof(OrderMessage);

		public OrderMessage() : base() { }

		public OrderMessage(Int32 id, String code, DateTime sentDate, DateTime receivedDate)
			: base(id, code, sentDate, receivedDate)
		{

		}
  }


	/// <summary>
	/// Object model class for OrderMessagesGennie (Generated by Gennie)
	/// </summary>
	[Serializable]
	public abstract class OrderMessageGennie
	{
		private const string CLASSNAME = nameof(OrderMessageGennie);


		/// <summary>
		/// Default constructor
		/// </summary>
		public OrderMessageGennie()
		{
		    //Empty constructor
		}


		/// <summary>
		/// Constructor with all parameters
		/// </summary>
		public OrderMessageGennie(Int32 id, String code, DateTime sentDate, DateTime receivedDate)
		{
			_id = id;
			_code = code;
			_sentDate = sentDate;
			_receivedDate = receivedDate;
		}


		/// <summary>
		/// Property: Id
		/// Description: (AutoIdentity) Unique identification of the order message
		/// </summary>
    public Int32 Id
		{
			set { _id = value; }
			get { return _id; }
		} protected Int32 _id;


		/// <summary>
		/// Property: Code
		/// Description: Unique key of this order message
		/// </summary>
    public String Code
		{
			set { _code = value; }
			get { return _code; }
		} protected String _code;


		/// <summary>
		/// Property: SentDate
		/// Description: Date and time the order message has been sent to MES
		/// </summary>
    public DateTime SentDate
		{
			set { _sentDate = value; }
			get { return _sentDate; }
		} protected DateTime _sentDate;


		/// <summary>
		/// Property: ReceivedDate
		/// Description: Date and time the order message has been inserted into the MES system
		/// </summary>
    public DateTime ReceivedDate
		{
			set { _receivedDate = value; }
			get { return _receivedDate; }
		} protected DateTime _receivedDate;


    /// <summary>
		/// Override the default ToString function to show all properties of the class
		/// </summary>
    public override string ToString()
    {
      return string.Format("OrderMessage:Id={0}, Code={1}, SentDate={2}, ReceivedDate={3}", 
			_id, _code, _sentDate, _receivedDate);
    }
    
    
		/// <summary>
		/// Override the default Equals function to compare class
		/// </summary>    
    public override bool Equals(object obj)
    {
			if (obj is Int32)
			{
				return (Id == (Int32)obj);
			}
			else
				if (obj is OrderMessage)
					return Equals((OrderMessage)obj);
			return false;

		}


		/// <summary>
		/// Equals function to compare class
		/// </summary>    
		public virtual bool Equals(OrderMessage obj)
		{
			return ((this.Id.Equals(((OrderMessage)obj).Id)));
		}


		/// <summary>
		/// Override the default GetHashCode
		/// </summary> 
		public override int GetHashCode()
		{
		  int result = 0;
		  result = Id.GetHashCode();

		  return result;
		}
		
  }
}
