using System;

namespace Actemium.L3IC.OrderManager.Model
{

	/// <summary>
	/// Object model class for Resources
	/// Description: The resources that are present in the plant for needed for production
	/// </summary>
	[Serializable]
	public partial class Resource : ResourceGennie
  {
		private const string CLASSNAME = nameof(Resource);

		public Resource() : base() { }

		public Resource(Int32 id, String code, String description)
			: base(id, code, description)
		{

		}
  }


	/// <summary>
	/// Object model class for ResourcesGennie (Generated by Gennie)
	/// </summary>
	[Serializable]
	public abstract class ResourceGennie
	{
		private const string CLASSNAME = nameof(ResourceGennie);


		/// <summary>
		/// Default constructor
		/// </summary>
		public ResourceGennie()
		{
		    //Empty constructor
		}


		/// <summary>
		/// Constructor with all parameters
		/// </summary>
		public ResourceGennie(Int32 id, String code, String description)
		{
			_id = id;
			_code = code;
			_description = description;
		}


		/// <summary>
		/// Property: Id
		/// Description: (AutoIdentity) Unique identification of the resource
		/// </summary>
    public Int32 Id
		{
			set { _id = value; }
			get { return _id; }
		} protected Int32 _id;


		/// <summary>
		/// Property: Code
		/// Description: Unique key of this resource
		/// </summary>
    public String Code
		{
			set { _code = value; }
			get { return _code; }
		} protected String _code;


		/// <summary>
		/// Property: Description
		/// Description: Description of this resource
		/// </summary>
    public String Description
		{
			set { _description = value; }
			get { return _description; }
		} protected String _description;


    /// <summary>
		/// Override the default ToString function to show all properties of the class
		/// </summary>
    public override string ToString()
    {
      return string.Format("Resource:Id={0}, Code={1}, Description={2}", 
			_id, _code, _description);
    }
    
    
		/// <summary>
		/// Override the default Equals function to compare class
		/// </summary>    
    public override bool Equals(object obj)
    {
			if (obj is Int32)
			{
				return (Id == (Int32)obj);
			}
			else
				if (obj is Resource)
					return Equals((Resource)obj);
			return false;

		}


		/// <summary>
		/// Equals function to compare class
		/// </summary>    
		public virtual bool Equals(Resource obj)
		{
			return ((this.Id.Equals(((Resource)obj).Id)));
		}


		/// <summary>
		/// Override the default GetHashCode
		/// </summary> 
		public override int GetHashCode()
		{
		  int result = 0;
		  result = Id.GetHashCode();

		  return result;
		}
		
  }
}
