using System;
using System.Text;
using System.Data;
using System.Data.Common;
using System.Collections.Generic;
using Actemium.Diagnostics;
using Actemium.Data.Common;
using Actemium.Data.Exceptions;

namespace Actemium.L3IC.OrderManager.DataAccess
{
	/// <summary>
	/// Data access to the data in table MaterialGroups in the database (Generated by Gennie)
	/// Description: All groups of material needed for production. Both raw as finished good material groups are defined in this table
	/// </summary>
	public partial class MaterialGroups : MaterialGroupsGennie
	{
		private const string CLASSNAME = nameof(MaterialGroups);

	}

	/// <summary>
	/// Data access to the data in table MaterialGroupsGennie in the database (Generated by Gennie)
	/// </summary>
	public abstract class MaterialGroupsGennie
	{
		private const string CLASSNAME = nameof(MaterialGroupsGennie);


		/// <summary>
		/// Add a new MaterialGroup to the database
		/// </summary>
		public virtual void Add(Model.MaterialGroup newMaterialGroup)
		{
			try
			{
				Trace.WriteVerbose("({0})", Trace.GetMethodName(), CLASSNAME, newMaterialGroup.ToString());
				var helper = Database.GetDbHelper();


				int recordsAffected = helper.ExecuteSPNonQuery(_storedProcedure_Add,
					helper.CreateInputParam("@Id", newMaterialGroup.Id),
					helper.CreateInputParam("@Code", newMaterialGroup.Code),
					helper.CreateInputParam("@Description", newMaterialGroup.Description));

				if (recordsAffected == 0)
					throw new DalNothingUpdatedException("Unable to add MaterialGroup with Id={0}", newMaterialGroup);

return;
			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, newMaterialGroup.ToString());
				throw DbHelper.TranslateException(ex);
			}
		}

    /// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_Add = "[dbo].[MaterialGroupsGennie_Add]";
		


		/// <summary>
		/// Delete the given MaterialGroup from the database
		/// </summary>
		public virtual void Delete(Model.MaterialGroup materialGroup)
		{
			try
			{
				Trace.WriteVerbose("({0})", Trace.GetMethodName(), CLASSNAME, materialGroup.ToString());

        var helper = Database.GetDbHelper();
				helper.ExecuteSPNonQuery(_storedProcedure_Delete,
					helper.CreateInputParam("@Id", materialGroup.Id));
			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, materialGroup.ToString());
				throw DbHelper.TranslateException(ex);
			}
		}

    /// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_Delete = "[dbo].[MaterialGroupsGennie_Delete]";



		/// <summary>
		/// Modify the given MaterialGroup in the database
		/// </summary>
		public virtual void Modify(Model.MaterialGroup modifiedMaterialGroup)
		{
			try
			{
				Trace.WriteVerbose("({0})", Trace.GetMethodName(), CLASSNAME, modifiedMaterialGroup.ToString());

				var helper = Database.GetDbHelper();
        int recordsAffected = helper.ExecuteSPNonQuery(_storedProcedure_Modify,
					helper.CreateInputParam("@Id", modifiedMaterialGroup.Id),
					helper.CreateInputParam("@Code", modifiedMaterialGroup.Code),
					helper.CreateInputParam("@Description", modifiedMaterialGroup.Description));

				if (recordsAffected == 0)
				{
					throw new DalNothingUpdatedException("No records were updated (Table: MaterialGroups). MaterialGroup=" + modifiedMaterialGroup.ToString());
				}
			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, modifiedMaterialGroup.ToString());
				throw DbHelper.TranslateException(ex);
			}
		}
		
            /// <summary>
            /// String containing stored procedure name
            /// </summary>
	    protected string _storedProcedure_Modify = "[dbo].[MaterialGroupsGennie_Modify]";
		
	/// <summary>
	/// Modify only the specified properties of the MaterialGroup 
	/// specified by:
	/// </summary>
		/// <param name="id">PK</param>
	/// <param name="propValues">Properties to update</param>
		public virtual void Modify( Int32 id,  params KeyValuePair<string,object>[] propValues)
		{
			 try
      {
        Trace.WriteVerbose("({0})", Trace.GetMethodName(), CLASSNAME, id);
        
        if (propValues.Length == 0)
        {
			Trace.WriteVerbose("No properties to update.", Trace.GetMethodName(), CLASSNAME);
			return;
		}
        
        var helper = Database.GetDbHelper();
        StringBuilder sqlStatement =  new StringBuilder("UPDATE [dbo].[MaterialGroups] SET ");
        List<DbParameter> parameterList = new List<DbParameter>();
        for (int i = 0; i < propValues.Length ; i++)
        { 
          sqlStatement.AppendFormat( "[{0}]=@{0}", propValues[i].Key);
          if (i< propValues.Length -1)
            sqlStatement.Append( ", ");

          parameterList.Add(helper.CreateInputParam("@" + propValues[i].Key, propValues[i].Value != null ? propValues[i].Value : DBNull.Value));
          
        }
        sqlStatement.Append(" WHERE ");
         sqlStatement.Append("[Id]=@Id");
			     parameterList.Add( helper.CreateInputParam("@Id", id));
			

              int recordsAffected = helper.ExecuteText(sqlStatement.ToString(),
                                              parameterList.ToArray());
        
        if (recordsAffected == 0)
        {
          throw new DalNothingUpdatedException(string.Format("No records were updated (Table: MaterialGroups). Id={0}", id));
        }

      }
      catch (Exception ex)
      {
        Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, id);
        throw DbHelper.TranslateException(ex);
      }

      }



		/// <summary>
		/// Get a MaterialGroup by id from the database
		/// </summary>
		public virtual Model.MaterialGroup GetById(Int32 id)
		{
			DbDataReader reader = null;
			try
			{
        var helper = Database.GetDbHelper();
                
        reader = helper.ExecuteSPReader(_storedProcedure_GetById,
					helper.CreateInputParam("@Id", id));
				
				Model.MaterialGroup result = null;

				if (reader.Read())
          result = CreateMaterialGroup(reader);

				return result;
			}
			catch (Exception ex)
			{
				Trace.WriteError("{0}", Trace.GetMethodName(), CLASSNAME, ex, id);
				throw DbHelper.TranslateException(ex);
			}
			finally 
			{
				if (reader != null)
					reader.Close();
			}
		}
		
    /// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_GetById = "[dbo].[MaterialGroupsGennie_GetById]";


		
		/// <summary>
		/// Get all MaterialGroup records from the database
		/// </summary>
		public virtual List<Model.MaterialGroup> GetAll()
		{
			DbDataReader reader = null;
			try
			{
        var helper = Database.GetDbHelper();
        reader = helper.ExecuteSPReader(_storedProcedure_GetAll);
								
				List<Model.MaterialGroup> result = new List<Model.MaterialGroup>();
				while (reader.Read())
				{
				  result.Add(CreateMaterialGroup(reader));
				}
				
				return result;
			}
			catch (Exception ex)
			{
				Trace.WriteError("()", Trace.GetMethodName(), CLASSNAME, ex);
				throw DbHelper.TranslateException(ex);
			}
			finally 
			{
				if (reader != null)
					reader.Close();
			}
		}
		
		/// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_GetAll = "[dbo].[MaterialGroupsGennie_GetAll]";
		
		
		
		/// <summary>
		/// Create a Model.MaterialGroup
		/// </summary>
		protected virtual Model.MaterialGroup CreateMaterialGroup(DbDataReader reader)
		{
			try
			{	
        Model.MaterialGroup result = new Model.MaterialGroup(
          (Int32)reader["Id"], 
          (String)reader["Code"], 
          (String)reader["Description"]
						);
				return result;
			}
			catch (Exception ex)
			{
				Trace.WriteError("", Trace.GetMethodName(), CLASSNAME, ex);
				throw DbHelper.TranslateException(ex);
			}
		}	
	}
}