using System;
using System.Text;
using System.Data;
using System.Data.Common;
using System.Collections.Generic;
using Actemium.Diagnostics;
using Actemium.Data.Common;
using Actemium.Data.Exceptions;

namespace Actemium.L3IC.OrderManager.DataAccess
{
	/// <summary>
	/// Data access to the data in table MaterialParameters in the database (Generated by Gennie)
	/// Description: Material specific parameters
	/// </summary>
	public partial class MaterialParameters : MaterialParametersGennie
	{
		private const string CLASSNAME = nameof(MaterialParameters);

	}

	/// <summary>
	/// Data access to the data in table MaterialParametersGennie in the database (Generated by Gennie)
	/// </summary>
	public abstract class MaterialParametersGennie
	{
		private const string CLASSNAME = nameof(MaterialParametersGennie);


		/// <summary>
		/// Add a new MaterialParameter to the database
		/// </summary>
		public virtual Int32 Add(Model.MaterialParameter newMaterialParameter)
		{
			try
			{
				Trace.WriteVerbose("({0})", Trace.GetMethodName(), CLASSNAME, newMaterialParameter.ToString());
				var helper = Database.GetDbHelper();
				DbParameter IdParam = helper.CreateOutputParam("@Id", DbType.Int32);

				int recordsAffected = helper.ExecuteSPNonQuery(_storedProcedure_Add,
					IdParam,
					helper.CreateInputParam("@Code", newMaterialParameter.Code),
					helper.CreateInputParam("@MaterialGroupId", newMaterialParameter.MaterialGroupId));

				if (recordsAffected == 0)
					throw new DalNothingUpdatedException("Unable to add MaterialParameter with Id={0}", newMaterialParameter);

				return (Int32)IdParam.Value;
			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, newMaterialParameter.ToString());
				throw DbHelper.TranslateException(ex);
			}
		}

    /// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_Add = "[dbo].[MaterialParametersGennie_Add]";
		


		/// <summary>
		/// Delete the given MaterialParameter from the database
		/// </summary>
		public virtual void Delete(Model.MaterialParameter materialParameter)
		{
			try
			{
				Trace.WriteVerbose("({0})", Trace.GetMethodName(), CLASSNAME, materialParameter.ToString());

        var helper = Database.GetDbHelper();
				helper.ExecuteSPNonQuery(_storedProcedure_Delete,
					helper.CreateInputParam("@Id", materialParameter.Id));
			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, materialParameter.ToString());
				throw DbHelper.TranslateException(ex);
			}
		}

    /// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_Delete = "[dbo].[MaterialParametersGennie_Delete]";



		/// <summary>
		/// Modify the given MaterialParameter in the database
		/// </summary>
		public virtual void Modify(Model.MaterialParameter modifiedMaterialParameter)
		{
			try
			{
				Trace.WriteVerbose("({0})", Trace.GetMethodName(), CLASSNAME, modifiedMaterialParameter.ToString());

				var helper = Database.GetDbHelper();
        int recordsAffected = helper.ExecuteSPNonQuery(_storedProcedure_Modify,
					helper.CreateInputParam("@Id", modifiedMaterialParameter.Id),
					helper.CreateInputParam("@Code", modifiedMaterialParameter.Code),
					helper.CreateInputParam("@MaterialGroupId", modifiedMaterialParameter.MaterialGroupId));

				if (recordsAffected == 0)
				{
					throw new DalNothingUpdatedException("No records were updated (Table: MaterialParameters). MaterialParameter=" + modifiedMaterialParameter.ToString());
				}
			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, modifiedMaterialParameter.ToString());
				throw DbHelper.TranslateException(ex);
			}
		}
		
            /// <summary>
            /// String containing stored procedure name
            /// </summary>
	    protected string _storedProcedure_Modify = "[dbo].[MaterialParametersGennie_Modify]";
		
	/// <summary>
	/// Modify only the specified properties of the MaterialParameter 
	/// specified by:
	/// </summary>
		/// <param name="id">PK</param>
	/// <param name="propValues">Properties to update</param>
		public virtual void Modify( Int32 id,  params KeyValuePair<string,object>[] propValues)
		{
			 try
      {
        Trace.WriteVerbose("({0})", Trace.GetMethodName(), CLASSNAME, id);
        
        if (propValues.Length == 0)
        {
			Trace.WriteVerbose("No properties to update.", Trace.GetMethodName(), CLASSNAME);
			return;
		}
        
        var helper = Database.GetDbHelper();
        StringBuilder sqlStatement =  new StringBuilder("UPDATE [dbo].[MaterialParameters] SET ");
        List<DbParameter> parameterList = new List<DbParameter>();
        for (int i = 0; i < propValues.Length ; i++)
        { 
          sqlStatement.AppendFormat( "[{0}]=@{0}", propValues[i].Key);
          if (i< propValues.Length -1)
            sqlStatement.Append( ", ");

          parameterList.Add(helper.CreateInputParam("@" + propValues[i].Key, propValues[i].Value != null ? propValues[i].Value : DBNull.Value));
          
        }
        sqlStatement.Append(" WHERE ");
         sqlStatement.Append("[Id]=@Id");
			     parameterList.Add( helper.CreateInputParam("@Id", id));
			

              int recordsAffected = helper.ExecuteText(sqlStatement.ToString(),
                                              parameterList.ToArray());
        
        if (recordsAffected == 0)
        {
          throw new DalNothingUpdatedException(string.Format("No records were updated (Table: MaterialParameters). Id={0}", id));
        }

      }
      catch (Exception ex)
      {
        Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, id);
        throw DbHelper.TranslateException(ex);
      }

      }



		/// <summary>
		/// Get a MaterialParameter by id from the database
		/// </summary>
		public virtual Model.MaterialParameter GetById(Int32 id)
		{
			DbDataReader reader = null;
			try
			{
        var helper = Database.GetDbHelper();
                
        reader = helper.ExecuteSPReader(_storedProcedure_GetById,
					helper.CreateInputParam("@Id", id));
				
				Model.MaterialParameter result = null;

				if (reader.Read())
          result = CreateMaterialParameter(reader);

				return result;
			}
			catch (Exception ex)
			{
				Trace.WriteError("{0}", Trace.GetMethodName(), CLASSNAME, ex, id);
				throw DbHelper.TranslateException(ex);
			}
			finally 
			{
				if (reader != null)
					reader.Close();
			}
		}
		
    /// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_GetById = "[dbo].[MaterialParametersGennie_GetById]";



		/// <summary>
		/// Get a MaterialParameter by MaterialGroupId from the database
		/// </summary>
		public virtual List<Model.MaterialParameter> GetByMaterialGroupId(Int32 materialGroupId)
		{
			DbDataReader reader = null;
			try
			{
        var helper = Database.GetDbHelper();
        reader = helper.ExecuteSPReader(_storedProcedure_GetByMaterialGroupId, 
					helper.CreateInputParam("@MaterialGroupId", materialGroupId));
                
        List<Model.MaterialParameter> result = new List<Model.MaterialParameter>();
				while (reader.Read())
				{
				  result.Add(CreateMaterialParameter(reader));
				}
				return result;

			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, materialGroupId);
				throw DbHelper.TranslateException(ex);
			}
			finally 
			{
				if (reader != null)
					reader.Close();
			}
		}
		
		/// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_GetByMaterialGroupId = "[dbo].[MaterialParametersGennie_GetByMaterialGroupId]";
		
		
		
		/// <summary>
		/// Get all MaterialParameter records from the database
		/// </summary>
		public virtual List<Model.MaterialParameter> GetAll()
		{
			DbDataReader reader = null;
			try
			{
        var helper = Database.GetDbHelper();
        reader = helper.ExecuteSPReader(_storedProcedure_GetAll);
								
				List<Model.MaterialParameter> result = new List<Model.MaterialParameter>();
				while (reader.Read())
				{
				  result.Add(CreateMaterialParameter(reader));
				}
				
				return result;
			}
			catch (Exception ex)
			{
				Trace.WriteError("()", Trace.GetMethodName(), CLASSNAME, ex);
				throw DbHelper.TranslateException(ex);
			}
			finally 
			{
				if (reader != null)
					reader.Close();
			}
		}
		
		/// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_GetAll = "[dbo].[MaterialParametersGennie_GetAll]";
		
		
		
		/// <summary>
		/// Create a Model.MaterialParameter
		/// </summary>
		protected virtual Model.MaterialParameter CreateMaterialParameter(DbDataReader reader)
		{
			try
			{	
        Model.MaterialParameter result = new Model.MaterialParameter(
          (Int32)reader["Id"], 
          (String)reader["Code"], 
          (Int32)reader["MaterialGroupId"]
						);
				return result;
			}
			catch (Exception ex)
			{
				Trace.WriteError("", Trace.GetMethodName(), CLASSNAME, ex);
				throw DbHelper.TranslateException(ex);
			}
		}	
	}
}