using System;
using System.Text;
using System.Data;
using System.Data.Common;
using System.Collections.Generic;
using Actemium.Diagnostics;
using Actemium.Data.Common;
using Actemium.Data.Exceptions;

namespace Actemium.L3IC.OrderManager.DataAccess
{
	/// <summary>
	/// Data access to the data in table Materials in the database (Generated by Gennie)
	/// Description: The raw and finished goods materials for the production
	/// </summary>
	public partial class Materials : MaterialsGennie
	{
		private const string CLASSNAME = nameof(Materials);

	}

	/// <summary>
	/// Data access to the data in table MaterialsGennie in the database (Generated by Gennie)
	/// </summary>
	public abstract class MaterialsGennie
	{
		private const string CLASSNAME = nameof(MaterialsGennie);


		/// <summary>
		/// Add a new Material to the database
		/// </summary>
		public virtual Int32 Add(Model.Material newMaterial)
		{
			try
			{
				Trace.WriteVerbose("({0})", Trace.GetMethodName(), CLASSNAME, newMaterial.ToString());
				var helper = Database.GetDbHelper();
				DbParameter IdParam = helper.CreateOutputParam("@Id", DbType.Int32);

				int recordsAffected = helper.ExecuteSPNonQuery(_storedProcedure_Add,
					IdParam,
					helper.CreateInputParam("@MaterialGroupId", newMaterial.MaterialGroupId),
					helper.CreateInputParam("@Code", newMaterial.Code),
					helper.CreateInputParam("@Description", newMaterial.Description));

				if (recordsAffected == 0)
					throw new DalNothingUpdatedException("Unable to add Material with Id={0}", newMaterial);

				return (Int32)IdParam.Value;
			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, newMaterial.ToString());
				throw DbHelper.TranslateException(ex);
			}
		}

    /// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_Add = "[dbo].[MaterialsGennie_Add]";
		


		/// <summary>
		/// Delete the given Material from the database
		/// </summary>
		public virtual void Delete(Model.Material material)
		{
			try
			{
				Trace.WriteVerbose("({0})", Trace.GetMethodName(), CLASSNAME, material.ToString());

        var helper = Database.GetDbHelper();
				helper.ExecuteSPNonQuery(_storedProcedure_Delete,
					helper.CreateInputParam("@Id", material.Id));
			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, material.ToString());
				throw DbHelper.TranslateException(ex);
			}
		}

    /// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_Delete = "[dbo].[MaterialsGennie_Delete]";



		/// <summary>
		/// Modify the given Material in the database
		/// </summary>
		public virtual void Modify(Model.Material modifiedMaterial)
		{
			try
			{
				Trace.WriteVerbose("({0})", Trace.GetMethodName(), CLASSNAME, modifiedMaterial.ToString());

				var helper = Database.GetDbHelper();
        int recordsAffected = helper.ExecuteSPNonQuery(_storedProcedure_Modify,
					helper.CreateInputParam("@Id", modifiedMaterial.Id),
					helper.CreateInputParam("@MaterialGroupId", modifiedMaterial.MaterialGroupId),
					helper.CreateInputParam("@Code", modifiedMaterial.Code),
					helper.CreateInputParam("@Description", modifiedMaterial.Description));

				if (recordsAffected == 0)
				{
					throw new DalNothingUpdatedException("No records were updated (Table: Materials). Material=" + modifiedMaterial.ToString());
				}
			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, modifiedMaterial.ToString());
				throw DbHelper.TranslateException(ex);
			}
		}
		
            /// <summary>
            /// String containing stored procedure name
            /// </summary>
	    protected string _storedProcedure_Modify = "[dbo].[MaterialsGennie_Modify]";
		
	/// <summary>
	/// Modify only the specified properties of the Material 
	/// specified by:
	/// </summary>
		/// <param name="id">PK</param>
	/// <param name="propValues">Properties to update</param>
		public virtual void Modify( Int32 id,  params KeyValuePair<string,object>[] propValues)
		{
			 try
      {
        Trace.WriteVerbose("({0})", Trace.GetMethodName(), CLASSNAME, id);
        
        if (propValues.Length == 0)
        {
			Trace.WriteVerbose("No properties to update.", Trace.GetMethodName(), CLASSNAME);
			return;
		}
        
        var helper = Database.GetDbHelper();
        StringBuilder sqlStatement =  new StringBuilder("UPDATE [dbo].[Materials] SET ");
        List<DbParameter> parameterList = new List<DbParameter>();
        for (int i = 0; i < propValues.Length ; i++)
        { 
          sqlStatement.AppendFormat( "[{0}]=@{0}", propValues[i].Key);
          if (i< propValues.Length -1)
            sqlStatement.Append( ", ");

          parameterList.Add(helper.CreateInputParam("@" + propValues[i].Key, propValues[i].Value != null ? propValues[i].Value : DBNull.Value));
          
        }
        sqlStatement.Append(" WHERE ");
         sqlStatement.Append("[Id]=@Id");
			     parameterList.Add( helper.CreateInputParam("@Id", id));
			

              int recordsAffected = helper.ExecuteText(sqlStatement.ToString(),
                                              parameterList.ToArray());
        
        if (recordsAffected == 0)
        {
          throw new DalNothingUpdatedException(string.Format("No records were updated (Table: Materials). Id={0}", id));
        }

      }
      catch (Exception ex)
      {
        Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, id);
        throw DbHelper.TranslateException(ex);
      }

      }



		/// <summary>
		/// Get a Material by id from the database
		/// </summary>
		public virtual Model.Material GetById(Int32 id)
		{
			DbDataReader reader = null;
			try
			{
        var helper = Database.GetDbHelper();
                
        reader = helper.ExecuteSPReader(_storedProcedure_GetById,
					helper.CreateInputParam("@Id", id));
				
				Model.Material result = null;

				if (reader.Read())
          result = CreateMaterial(reader);

				return result;
			}
			catch (Exception ex)
			{
				Trace.WriteError("{0}", Trace.GetMethodName(), CLASSNAME, ex, id);
				throw DbHelper.TranslateException(ex);
			}
			finally 
			{
				if (reader != null)
					reader.Close();
			}
		}
		
    /// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_GetById = "[dbo].[MaterialsGennie_GetById]";



		/// <summary>
		/// Get a Material by MaterialGroupId from the database
		/// </summary>
		public virtual List<Model.Material> GetByMaterialGroupId(Int32 materialGroupId)
		{
			DbDataReader reader = null;
			try
			{
        var helper = Database.GetDbHelper();
        reader = helper.ExecuteSPReader(_storedProcedure_GetByMaterialGroupId, 
					helper.CreateInputParam("@MaterialGroupId", materialGroupId));
                
        List<Model.Material> result = new List<Model.Material>();
				while (reader.Read())
				{
				  result.Add(CreateMaterial(reader));
				}
				return result;

			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, materialGroupId);
				throw DbHelper.TranslateException(ex);
			}
			finally 
			{
				if (reader != null)
					reader.Close();
			}
		}
		
		/// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_GetByMaterialGroupId = "[dbo].[MaterialsGennie_GetByMaterialGroupId]";
		
		
		
		/// <summary>
		/// Get all Material records from the database
		/// </summary>
		public virtual List<Model.Material> GetAll()
		{
			DbDataReader reader = null;
			try
			{
        var helper = Database.GetDbHelper();
        reader = helper.ExecuteSPReader(_storedProcedure_GetAll);
								
				List<Model.Material> result = new List<Model.Material>();
				while (reader.Read())
				{
				  result.Add(CreateMaterial(reader));
				}
				
				return result;
			}
			catch (Exception ex)
			{
				Trace.WriteError("()", Trace.GetMethodName(), CLASSNAME, ex);
				throw DbHelper.TranslateException(ex);
			}
			finally 
			{
				if (reader != null)
					reader.Close();
			}
		}
		
		/// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_GetAll = "[dbo].[MaterialsGennie_GetAll]";
		
		
		
		/// <summary>
		/// Create a Model.Material
		/// </summary>
		protected virtual Model.Material CreateMaterial(DbDataReader reader)
		{
			try
			{	
        Model.Material result = new Model.Material(
          (Int32)reader["Id"], 
          (Int32)reader["MaterialGroupId"], 
          (Int32)reader["Code"], 
          (String)reader["Description"]
						);
				return result;
			}
			catch (Exception ex)
			{
				Trace.WriteError("", Trace.GetMethodName(), CLASSNAME, ex);
				throw DbHelper.TranslateException(ex);
			}
		}	
	}
}