using System;
using System.Text;
using System.Data;
using System.Data.Common;
using System.Collections.Generic;
using Actemium.Diagnostics;
using Actemium.Data.Common;
using Actemium.Data.Exceptions;

namespace Actemium.L3IC.OrderManager.DataAccess
{
	/// <summary>
	/// Data access to the data in table OrderMessages in the database (Generated by Gennie)
	/// Description: Logging of all messages that have been received for orders from an external system
	/// </summary>
	public partial class OrderMessages : OrderMessagesGennie
	{
		private const string CLASSNAME = nameof(OrderMessages);

	}

	/// <summary>
	/// Data access to the data in table OrderMessagesGennie in the database (Generated by Gennie)
	/// </summary>
	public abstract class OrderMessagesGennie
	{
		private const string CLASSNAME = nameof(OrderMessagesGennie);


		/// <summary>
		/// Add a new OrderMessage to the database
		/// </summary>
		public virtual Int32 Add(Model.OrderMessage newOrderMessage)
		{
			try
			{
				Trace.WriteVerbose("({0})", Trace.GetMethodName(), CLASSNAME, newOrderMessage.ToString());
				var helper = Database.GetDbHelper();
				DbParameter IdParam = helper.CreateOutputParam("@Id", DbType.Int32);

				int recordsAffected = helper.ExecuteSPNonQuery(_storedProcedure_Add,
					IdParam,
					helper.CreateInputParam("@Code", newOrderMessage.Code),
					helper.CreateInputParam("@SentDate", newOrderMessage.SentDate),
					helper.CreateInputParam("@ReceivedDate", newOrderMessage.ReceivedDate));

				if (recordsAffected == 0)
					throw new DalNothingUpdatedException("Unable to add OrderMessage with Id={0}", newOrderMessage);

				return (Int32)IdParam.Value;
			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, newOrderMessage.ToString());
				throw DbHelper.TranslateException(ex);
			}
		}

    /// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_Add = "[dbo].[OrderMessagesGennie_Add]";
		


		/// <summary>
		/// Delete the given OrderMessage from the database
		/// </summary>
		public virtual void Delete(Model.OrderMessage orderMessage)
		{
			try
			{
				Trace.WriteVerbose("({0})", Trace.GetMethodName(), CLASSNAME, orderMessage.ToString());

        var helper = Database.GetDbHelper();
				helper.ExecuteSPNonQuery(_storedProcedure_Delete,
					helper.CreateInputParam("@Id", orderMessage.Id));
			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, orderMessage.ToString());
				throw DbHelper.TranslateException(ex);
			}
		}

    /// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_Delete = "[dbo].[OrderMessagesGennie_Delete]";



		/// <summary>
		/// Modify the given OrderMessage in the database
		/// </summary>
		public virtual void Modify(Model.OrderMessage modifiedOrderMessage)
		{
			try
			{
				Trace.WriteVerbose("({0})", Trace.GetMethodName(), CLASSNAME, modifiedOrderMessage.ToString());

				var helper = Database.GetDbHelper();
        int recordsAffected = helper.ExecuteSPNonQuery(_storedProcedure_Modify,
					helper.CreateInputParam("@Id", modifiedOrderMessage.Id),
					helper.CreateInputParam("@Code", modifiedOrderMessage.Code),
					helper.CreateInputParam("@SentDate", modifiedOrderMessage.SentDate),
					helper.CreateInputParam("@ReceivedDate", modifiedOrderMessage.ReceivedDate));

				if (recordsAffected == 0)
				{
					throw new DalNothingUpdatedException("No records were updated (Table: OrderMessages). OrderMessage=" + modifiedOrderMessage.ToString());
				}
			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, modifiedOrderMessage.ToString());
				throw DbHelper.TranslateException(ex);
			}
		}
		
            /// <summary>
            /// String containing stored procedure name
            /// </summary>
	    protected string _storedProcedure_Modify = "[dbo].[OrderMessagesGennie_Modify]";
		
	/// <summary>
	/// Modify only the specified properties of the OrderMessage 
	/// specified by:
	/// </summary>
		/// <param name="id">PK</param>
	/// <param name="propValues">Properties to update</param>
		public virtual void Modify( Int32 id,  params KeyValuePair<string,object>[] propValues)
		{
			 try
      {
        Trace.WriteVerbose("({0})", Trace.GetMethodName(), CLASSNAME, id);
        
        if (propValues.Length == 0)
        {
			Trace.WriteVerbose("No properties to update.", Trace.GetMethodName(), CLASSNAME);
			return;
		}
        
        var helper = Database.GetDbHelper();
        StringBuilder sqlStatement =  new StringBuilder("UPDATE [dbo].[OrderMessages] SET ");
        List<DbParameter> parameterList = new List<DbParameter>();
        for (int i = 0; i < propValues.Length ; i++)
        { 
          sqlStatement.AppendFormat( "[{0}]=@{0}", propValues[i].Key);
          if (i< propValues.Length -1)
            sqlStatement.Append( ", ");

          parameterList.Add(helper.CreateInputParam("@" + propValues[i].Key, propValues[i].Value != null ? propValues[i].Value : DBNull.Value));
          
        }
        sqlStatement.Append(" WHERE ");
         sqlStatement.Append("[Id]=@Id");
			     parameterList.Add( helper.CreateInputParam("@Id", id));
			

              int recordsAffected = helper.ExecuteText(sqlStatement.ToString(),
                                              parameterList.ToArray());
        
        if (recordsAffected == 0)
        {
          throw new DalNothingUpdatedException(string.Format("No records were updated (Table: OrderMessages). Id={0}", id));
        }

      }
      catch (Exception ex)
      {
        Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, id);
        throw DbHelper.TranslateException(ex);
      }

      }



		/// <summary>
		/// Get a OrderMessage by id from the database
		/// </summary>
		public virtual Model.OrderMessage GetById(Int32 id)
		{
			DbDataReader reader = null;
			try
			{
        var helper = Database.GetDbHelper();
                
        reader = helper.ExecuteSPReader(_storedProcedure_GetById,
					helper.CreateInputParam("@Id", id));
				
				Model.OrderMessage result = null;

				if (reader.Read())
          result = CreateOrderMessage(reader);

				return result;
			}
			catch (Exception ex)
			{
				Trace.WriteError("{0}", Trace.GetMethodName(), CLASSNAME, ex, id);
				throw DbHelper.TranslateException(ex);
			}
			finally 
			{
				if (reader != null)
					reader.Close();
			}
		}
		
    /// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_GetById = "[dbo].[OrderMessagesGennie_GetById]";


		
		/// <summary>
		/// Get all OrderMessage records from the database
		/// </summary>
		public virtual List<Model.OrderMessage> GetAll()
		{
			DbDataReader reader = null;
			try
			{
        var helper = Database.GetDbHelper();
        reader = helper.ExecuteSPReader(_storedProcedure_GetAll);
								
				List<Model.OrderMessage> result = new List<Model.OrderMessage>();
				while (reader.Read())
				{
				  result.Add(CreateOrderMessage(reader));
				}
				
				return result;
			}
			catch (Exception ex)
			{
				Trace.WriteError("()", Trace.GetMethodName(), CLASSNAME, ex);
				throw DbHelper.TranslateException(ex);
			}
			finally 
			{
				if (reader != null)
					reader.Close();
			}
		}
		
		/// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_GetAll = "[dbo].[OrderMessagesGennie_GetAll]";
		
		
		
		/// <summary>
		/// Create a Model.OrderMessage
		/// </summary>
		protected virtual Model.OrderMessage CreateOrderMessage(DbDataReader reader)
		{
			try
			{	
        Model.OrderMessage result = new Model.OrderMessage(
          (Int32)reader["Id"], 
          (String)reader["Code"], 
          (DateTime)reader["SentDate"], 
          (DateTime)reader["ReceivedDate"]
						);
				return result;
			}
			catch (Exception ex)
			{
				Trace.WriteError("", Trace.GetMethodName(), CLASSNAME, ex);
				throw DbHelper.TranslateException(ex);
			}
		}	
	}
}