using System;
using System.Text;
using System.Data;
using System.Data.Common;
using System.Collections.Generic;
using Actemium.Diagnostics;
using Actemium.Data.Common;
using Actemium.Data.Exceptions;

namespace Actemium.L3IC.OrderManager.DataAccess
{
	/// <summary>
	/// Data access to the data in table Orders in the database (Generated by Gennie)
	/// Description: All production orders
	/// </summary>
	public partial class Orders : OrdersGennie
	{
		private const string CLASSNAME = nameof(Orders);

	}

	/// <summary>
	/// Data access to the data in table OrdersGennie in the database (Generated by Gennie)
	/// </summary>
	public abstract class OrdersGennie
	{
		private const string CLASSNAME = nameof(OrdersGennie);


		/// <summary>
		/// Add a new Order to the database
		/// </summary>
		public virtual Int32 Add(Model.Order newOrder)
		{
			try
			{
				Trace.WriteVerbose("({0})", Trace.GetMethodName(), CLASSNAME, newOrder.ToString());
				var helper = Database.GetDbHelper();
				DbParameter IdParam = helper.CreateOutputParam("@Id", DbType.Int32);

				int recordsAffected = helper.ExecuteSPNonQuery(_storedProcedure_Add,
					IdParam,
					helper.CreateInputParam("@OrderMessageId", newOrder.OrderMessageId),
					helper.CreateInputParam("@Code", newOrder.Code),
					helper.CreateInputParam("@MaterialId", newOrder.MaterialId),
					helper.CreateInputParam("@ResourceId", newOrder.ResourceId),
					helper.CreateInputParam("@TargetQuantity", newOrder.TargetQuantity),
					helper.CreateInputParam("@UOM", newOrder.UOM),
					helper.CreateInputParam("@PlannedStartDate", newOrder.PlannedStartDate),
					helper.CreateInputParam("@StartDate", newOrder.StartDate.HasValue ? (object)newOrder.StartDate : DBNull.Value),
					helper.CreateInputParam("@FinishDate", newOrder.FinishDate.HasValue ? (object)newOrder.FinishDate : DBNull.Value));

				if (recordsAffected == 0)
					throw new DalNothingUpdatedException("Unable to add Order with Id={0}", newOrder);

				return (Int32)IdParam.Value;
			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, newOrder.ToString());
				throw DbHelper.TranslateException(ex);
			}
		}

    /// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_Add = "[dbo].[OrdersGennie_Add]";
		


		/// <summary>
		/// Delete the given Order from the database
		/// </summary>
		public virtual void Delete(Model.Order order)
		{
			try
			{
				Trace.WriteVerbose("({0})", Trace.GetMethodName(), CLASSNAME, order.ToString());

        var helper = Database.GetDbHelper();
				helper.ExecuteSPNonQuery(_storedProcedure_Delete,
					helper.CreateInputParam("@Id", order.Id));
			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, order.ToString());
				throw DbHelper.TranslateException(ex);
			}
		}

    /// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_Delete = "[dbo].[OrdersGennie_Delete]";



		/// <summary>
		/// Modify the given Order in the database
		/// </summary>
		public virtual void Modify(Model.Order modifiedOrder)
		{
			try
			{
				Trace.WriteVerbose("({0})", Trace.GetMethodName(), CLASSNAME, modifiedOrder.ToString());

				var helper = Database.GetDbHelper();
        int recordsAffected = helper.ExecuteSPNonQuery(_storedProcedure_Modify,
					helper.CreateInputParam("@Id", modifiedOrder.Id),
					helper.CreateInputParam("@OrderMessageId", modifiedOrder.OrderMessageId),
					helper.CreateInputParam("@Code", modifiedOrder.Code),
					helper.CreateInputParam("@MaterialId", modifiedOrder.MaterialId),
					helper.CreateInputParam("@ResourceId", modifiedOrder.ResourceId),
					helper.CreateInputParam("@TargetQuantity", modifiedOrder.TargetQuantity),
					helper.CreateInputParam("@UOM", modifiedOrder.UOM),
					helper.CreateInputParam("@PlannedStartDate", modifiedOrder.PlannedStartDate),
					helper.CreateInputParam("@StartDate", modifiedOrder.StartDate.HasValue ? (object)modifiedOrder.StartDate : DBNull.Value),
					helper.CreateInputParam("@FinishDate", modifiedOrder.FinishDate.HasValue ? (object)modifiedOrder.FinishDate : DBNull.Value));

				if (recordsAffected == 0)
				{
					throw new DalNothingUpdatedException("No records were updated (Table: Orders). Order=" + modifiedOrder.ToString());
				}
			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, modifiedOrder.ToString());
				throw DbHelper.TranslateException(ex);
			}
		}
		
            /// <summary>
            /// String containing stored procedure name
            /// </summary>
	    protected string _storedProcedure_Modify = "[dbo].[OrdersGennie_Modify]";
		
	/// <summary>
	/// Modify only the specified properties of the Order 
	/// specified by:
	/// </summary>
		/// <param name="id">PK</param>
	/// <param name="propValues">Properties to update</param>
		public virtual void Modify( Int32 id,  params KeyValuePair<string,object>[] propValues)
		{
			 try
      {
        Trace.WriteVerbose("({0})", Trace.GetMethodName(), CLASSNAME, id);
        
        if (propValues.Length == 0)
        {
			Trace.WriteVerbose("No properties to update.", Trace.GetMethodName(), CLASSNAME);
			return;
		}
        
        var helper = Database.GetDbHelper();
        StringBuilder sqlStatement =  new StringBuilder("UPDATE [dbo].[Orders] SET ");
        List<DbParameter> parameterList = new List<DbParameter>();
        for (int i = 0; i < propValues.Length ; i++)
        { 
          sqlStatement.AppendFormat( "[{0}]=@{0}", propValues[i].Key);
          if (i< propValues.Length -1)
            sqlStatement.Append( ", ");

          parameterList.Add(helper.CreateInputParam("@" + propValues[i].Key, propValues[i].Value != null ? propValues[i].Value : DBNull.Value));
          
        }
        sqlStatement.Append(" WHERE ");
         sqlStatement.Append("[Id]=@Id");
			     parameterList.Add( helper.CreateInputParam("@Id", id));
			

              int recordsAffected = helper.ExecuteText(sqlStatement.ToString(),
                                              parameterList.ToArray());
        
        if (recordsAffected == 0)
        {
          throw new DalNothingUpdatedException(string.Format("No records were updated (Table: Orders). Id={0}", id));
        }

      }
      catch (Exception ex)
      {
        Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, id);
        throw DbHelper.TranslateException(ex);
      }

      }



		/// <summary>
		/// Get a Order by id from the database
		/// </summary>
		public virtual Model.Order GetById(Int32 id)
		{
			DbDataReader reader = null;
			try
			{
        var helper = Database.GetDbHelper();
                
        reader = helper.ExecuteSPReader(_storedProcedure_GetById,
					helper.CreateInputParam("@Id", id));
				
				Model.Order result = null;

				if (reader.Read())
          result = CreateOrder(reader);

				return result;
			}
			catch (Exception ex)
			{
				Trace.WriteError("{0}", Trace.GetMethodName(), CLASSNAME, ex, id);
				throw DbHelper.TranslateException(ex);
			}
			finally 
			{
				if (reader != null)
					reader.Close();
			}
		}
		
    /// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_GetById = "[dbo].[OrdersGennie_GetById]";



		/// <summary>
		/// Get a Order by OrderMessageId from the database
		/// </summary>
		public virtual List<Model.Order> GetByOrderMessageId(Int32 orderMessageId)
		{
			DbDataReader reader = null;
			try
			{
        var helper = Database.GetDbHelper();
        reader = helper.ExecuteSPReader(_storedProcedure_GetByOrderMessageId, 
					helper.CreateInputParam("@OrderMessageId", orderMessageId));
                
        List<Model.Order> result = new List<Model.Order>();
				while (reader.Read())
				{
				  result.Add(CreateOrder(reader));
				}
				return result;

			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, orderMessageId);
				throw DbHelper.TranslateException(ex);
			}
			finally 
			{
				if (reader != null)
					reader.Close();
			}
		}
		
		/// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_GetByOrderMessageId = "[dbo].[OrdersGennie_GetByOrderMessageId]";
		
		

		/// <summary>
		/// Get a Order by MaterialId from the database
		/// </summary>
		public virtual List<Model.Order> GetByMaterialId(Int32 materialId)
		{
			DbDataReader reader = null;
			try
			{
        var helper = Database.GetDbHelper();
        reader = helper.ExecuteSPReader(_storedProcedure_GetByMaterialId, 
					helper.CreateInputParam("@MaterialId", materialId));
                
        List<Model.Order> result = new List<Model.Order>();
				while (reader.Read())
				{
				  result.Add(CreateOrder(reader));
				}
				return result;

			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, materialId);
				throw DbHelper.TranslateException(ex);
			}
			finally 
			{
				if (reader != null)
					reader.Close();
			}
		}
		
		/// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_GetByMaterialId = "[dbo].[OrdersGennie_GetByMaterialId]";
		
		

		/// <summary>
		/// Get a Order by ResourceId from the database
		/// </summary>
		public virtual List<Model.Order> GetByResourceId(Int32 resourceId)
		{
			DbDataReader reader = null;
			try
			{
        var helper = Database.GetDbHelper();
        reader = helper.ExecuteSPReader(_storedProcedure_GetByResourceId, 
					helper.CreateInputParam("@ResourceId", resourceId));
                
        List<Model.Order> result = new List<Model.Order>();
				while (reader.Read())
				{
				  result.Add(CreateOrder(reader));
				}
				return result;

			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", Trace.GetMethodName(), CLASSNAME, ex, resourceId);
				throw DbHelper.TranslateException(ex);
			}
			finally 
			{
				if (reader != null)
					reader.Close();
			}
		}
		
		/// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_GetByResourceId = "[dbo].[OrdersGennie_GetByResourceId]";
		
		
		
		/// <summary>
		/// Get all Order records from the database
		/// </summary>
		public virtual List<Model.Order> GetAll()
		{
			DbDataReader reader = null;
			try
			{
        var helper = Database.GetDbHelper();
        reader = helper.ExecuteSPReader(_storedProcedure_GetAll);
								
				List<Model.Order> result = new List<Model.Order>();
				while (reader.Read())
				{
				  result.Add(CreateOrder(reader));
				}
				
				return result;
			}
			catch (Exception ex)
			{
				Trace.WriteError("()", Trace.GetMethodName(), CLASSNAME, ex);
				throw DbHelper.TranslateException(ex);
			}
			finally 
			{
				if (reader != null)
					reader.Close();
			}
		}
		
		/// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_GetAll = "[dbo].[OrdersGennie_GetAll]";
		
		
		
		/// <summary>
		/// Create a Model.Order
		/// </summary>
		protected virtual Model.Order CreateOrder(DbDataReader reader)
		{
			try
			{	
        Model.Order result = new Model.Order(
          (Int32)reader["Id"], 
          (Int32)reader["OrderMessageId"], 
          (String)reader["Code"], 
          (Int32)reader["MaterialId"], 
          (Int32)reader["ResourceId"], 
          (Decimal)reader["TargetQuantity"], 
          (String)reader["UOM"], 
          (DateTime)reader["PlannedStartDate"], 
          reader["StartDate"] != DBNull.Value ? (DateTime?)          reader["StartDate"] : null, 
          reader["FinishDate"] != DBNull.Value ? (DateTime?)          reader["FinishDate"] : null
						);
				return result;
			}
			catch (Exception ex)
			{
				Trace.WriteError("", Trace.GetMethodName(), CLASSNAME, ex);
				throw DbHelper.TranslateException(ex);
			}
		}	
	}
}