using System;
using System.Text;
using System.Data;
using System.Data.Common;
using System.Collections.Generic;
using Actemium.Diagnostics;
using Actemium.Data.Common;
using Actemium.Data.Exceptions;

namespace Actemium.ApplicationSettings.DataAccess
{
	/// <summary>
	/// Data access to the data in table ApplicationSettingsCategories in the database (Generated by Gennie)
	/// </summary>
	public partial class ApplicationSettingsCategories : ApplicationSettingsCategoriesGennie
	{
		private const string CLASSNAME = nameof(ApplicationSettingsCategories);

	}

	/// <summary>
	/// Data access to the data in table ApplicationSettingsCategoriesGennie in the database (Generated by Gennie)
	/// </summary>
	public abstract class ApplicationSettingsCategoriesGennie
	{
		private const string CLASSNAME = nameof(ApplicationSettingsCategoriesGennie);


		/// <summary>
		/// Add a new ApplicationSettingsCategory to the database
		/// </summary>
		public virtual void Add(Model.ApplicationSettingsCategory newApplicationSettingsCategory)
		{
			try
			{
				Trace.WriteVerbose("({0})", "Add", CLASSNAME, newApplicationSettingsCategory.ToString());
				var helper = Database.GetDbHelper();


				int recordsAffected = helper.ExecuteSPNonQuery(_storedProcedure_Add,
					helper.CreateInputParam("@ApplicationSettingsCategoryId", newApplicationSettingsCategory.ApplicationSettingsCategoryId),
					helper.CreateInputParam("@Name", newApplicationSettingsCategory.Name),
					helper.CreateInputParam("@Description", newApplicationSettingsCategory.Description));

				if (recordsAffected == 0)
					throw new DalNothingUpdatedException("Unable to add ApplicationSettingsCategory with ApplicationSettingsCategoryId={0}", newApplicationSettingsCategory);

return;
			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", "Add", CLASSNAME, ex, newApplicationSettingsCategory.ToString());
				throw DbHelper.TranslateException(ex);
			}
		}

    /// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_Add = "[AS].[ApplicationSettingsCategoriesGennie_Add]";
		


		/// <summary>
		/// Delete the given ApplicationSettingsCategory from the database
		/// </summary>
		public virtual void Delete(Model.ApplicationSettingsCategory applicationSettingsCategory)
		{
			try
			{
				Trace.WriteVerbose("({0})", "Delete", CLASSNAME, applicationSettingsCategory.ToString());

        var helper = Database.GetDbHelper();
				helper.ExecuteSPNonQuery(_storedProcedure_Delete,
					helper.CreateInputParam("@ApplicationSettingsCategoryId", applicationSettingsCategory.ApplicationSettingsCategoryId));
			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", "Delete", CLASSNAME, ex, applicationSettingsCategory.ToString());
				throw DbHelper.TranslateException(ex);
			}
		}

    /// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_Delete = "[AS].[ApplicationSettingsCategoriesGennie_Delete]";



		/// <summary>
		/// Modify the given ApplicationSettingsCategory in the database
		/// </summary>
		public virtual void Modify(Model.ApplicationSettingsCategory modifiedApplicationSettingsCategory)
		{
			try
			{
				Trace.WriteVerbose("({0})", "Modify", CLASSNAME, modifiedApplicationSettingsCategory.ToString());

				var helper = Database.GetDbHelper();
        int recordsAffected = helper.ExecuteSPNonQuery(_storedProcedure_Modify,
					helper.CreateInputParam("@ApplicationSettingsCategoryId", modifiedApplicationSettingsCategory.ApplicationSettingsCategoryId),
					helper.CreateInputParam("@Name", modifiedApplicationSettingsCategory.Name),
					helper.CreateInputParam("@Description", modifiedApplicationSettingsCategory.Description));

				if (recordsAffected == 0)
				{
					throw new DalNothingUpdatedException("No records were updated (Table: ApplicationSettingsCategories). ApplicationSettingsCategory=" + modifiedApplicationSettingsCategory.ToString());
				}
			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", "Modify", CLASSNAME, ex, modifiedApplicationSettingsCategory.ToString());
				throw DbHelper.TranslateException(ex);
			}
		}
		
            /// <summary>
            /// String containing stored procedure name
            /// </summary>
	    protected string _storedProcedure_Modify = "[AS].[ApplicationSettingsCategoriesGennie_Modify]";
		
	/// <summary>
	/// Modify only the specified properties of the ApplicationSettingsCategory 
	/// specified by:
	/// </summary>
		/// <param name="applicationSettingsCategoryId">PK</param>
	/// <param name="propValues">Properties to update</param>
		public virtual void Modify( Int32 applicationSettingsCategoryId,  params KeyValuePair<string,object>[] propValues)
		{
			 try
      {
        Trace.WriteVerbose("({0})", "Modify", CLASSNAME, applicationSettingsCategoryId);
        
        if (propValues.Length == 0)
        {
			Trace.WriteVerbose("No properties to update.", "Modify", CLASSNAME);
			return;
		}
        
        var helper = Database.GetDbHelper();
        StringBuilder sqlStatement =  new StringBuilder("UPDATE [AS].[ApplicationSettingsCategories] SET ");
        List<DbParameter> parameterList = new List<DbParameter>();
        for (int i = 0; i < propValues.Length ; i++)
        { 
          sqlStatement.AppendFormat( "[{0}]=@{0}", propValues[i].Key);
          if (i< propValues.Length -1)
            sqlStatement.Append( ", ");

          parameterList.Add(helper.CreateInputParam("@" + propValues[i].Key, propValues[i].Value != null ? propValues[i].Value : DBNull.Value));
          
        }
        sqlStatement.Append(" WHERE ");
         sqlStatement.Append("[ApplicationSettingsCategoryId]=@ApplicationSettingsCategoryId");
			     parameterList.Add( helper.CreateInputParam("@ApplicationSettingsCategoryId", applicationSettingsCategoryId));
			

              int recordsAffected = helper.ExecuteText(sqlStatement.ToString(),
                                              parameterList.ToArray());
        
        if (recordsAffected == 0)
        {
          throw new DalNothingUpdatedException(string.Format("No records were updated (Table: ApplicationSettingsCategories). Id={0}", applicationSettingsCategoryId));
        }

      }
      catch (Exception ex)
      {
        Trace.WriteError("({0})", "Modify", CLASSNAME, ex, applicationSettingsCategoryId);
        throw DbHelper.TranslateException(ex);
      }

      }



		/// <summary>
		/// Get a ApplicationSettingsCategory by id from the database
		/// </summary>
		public virtual Model.ApplicationSettingsCategory GetById(Int32 applicationSettingsCategoryId)
		{
			DbDataReader reader = null;
			try
			{
        var helper = Database.GetDbHelper();
                
        reader = helper.ExecuteSPReader(_storedProcedure_GetById,
					helper.CreateInputParam("@ApplicationSettingsCategoryId", applicationSettingsCategoryId));
				
				Model.ApplicationSettingsCategory result = null;

				if (reader.Read())
          result = CreateApplicationSettingsCategory(reader);

				return result;
			}
			catch (Exception ex)
			{
				Trace.WriteError("{0}", "GetById", CLASSNAME, ex, applicationSettingsCategoryId);
				throw DbHelper.TranslateException(ex);
			}
			finally 
			{
				if (reader != null)
					reader.Close();
			}
		}
		
    /// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_GetById = "[AS].[ApplicationSettingsCategoriesGennie_GetById]";


		
		/// <summary>
		/// Get all ApplicationSettingsCategory records from the database
		/// </summary>
		public virtual List<Model.ApplicationSettingsCategory> GetAll()
		{
			DbDataReader reader = null;
			try
			{
        var helper = Database.GetDbHelper();
        reader = helper.ExecuteSPReader(_storedProcedure_GetAll);
								
				List<Model.ApplicationSettingsCategory> result = new List<Model.ApplicationSettingsCategory>();
				while (reader.Read())
				{
				  result.Add(CreateApplicationSettingsCategory(reader));
				}
				
				return result;
			}
			catch (Exception ex)
			{
				Trace.WriteError("()", "GetAll", CLASSNAME, ex);
				throw DbHelper.TranslateException(ex);
			}
			finally 
			{
				if (reader != null)
					reader.Close();
			}
		}
		
		/// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_GetAll = "[AS].[ApplicationSettingsCategoriesGennie_GetAll]";
		
		
		
		/// <summary>
		/// Create a Model.ApplicationSettingsCategory
		/// </summary>
		protected virtual Model.ApplicationSettingsCategory CreateApplicationSettingsCategory(DbDataReader reader)
		{
			try
			{	
        Model.ApplicationSettingsCategory result = new Model.ApplicationSettingsCategory(
          (Int32)reader["ApplicationSettingsCategoryId"], 
          (String)reader["Name"], 
          (String)reader["Description"]
						);
				return result;
			}
			catch (Exception ex)
			{
				Trace.WriteError("", "CreateApplicationSettingsCategory", CLASSNAME, ex);
				throw DbHelper.TranslateException(ex);
			}
		}	
	}
}