using System;
using System.Text;
using System.Data;
using System.Data.Common;
using System.Collections.Generic;
using Actemium.Diagnostics;
using Actemium.Data.Common;
using Actemium.Data.Exceptions;

namespace Actemium.ApplicationSettings.DataAccess
{
	/// <summary>
	/// Data access to the data in table DataSources in the database (Generated by Gennie)
	/// </summary>
	public partial class DataSources : DataSourcesGennie
	{
		private const string CLASSNAME = nameof(DataSources);

	}

	/// <summary>
	/// Data access to the data in table DataSourcesGennie in the database (Generated by Gennie)
	/// </summary>
	public abstract class DataSourcesGennie
	{
		private const string CLASSNAME = nameof(DataSourcesGennie);


		/// <summary>
		/// Add a new DataSource to the database
		/// </summary>
		public virtual Int32 Add(Model.DataSource newDataSource)
		{
			try
			{
				Trace.WriteVerbose("({0})", "Add", CLASSNAME, newDataSource.ToString());
				var helper = Database.GetDbHelper();
				DbParameter IdParam = helper.CreateOutputParam("@Id", DbType.Int32);

				int recordsAffected = helper.ExecuteSPNonQuery(_storedProcedure_Add,
					IdParam,
					helper.CreateInputParam("@ListName", newDataSource.ListName),
					helper.CreateInputParam("@Object_Id", newDataSource.Object_Id),
					helper.CreateInputParam("@Key_Column_Id", newDataSource.Key_Column_Id),
					helper.CreateInputParam("@Value_Column_Id", newDataSource.Value_Column_Id));

				if (recordsAffected == 0)
					throw new DalNothingUpdatedException("Unable to add DataSource with Id={0}", newDataSource);

				return (Int32)IdParam.Value;
			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", "Add", CLASSNAME, ex, newDataSource.ToString());
				throw DbHelper.TranslateException(ex);
			}
		}

    /// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_Add = "[AS].[DataSourcesGennie_Add]";
		


		/// <summary>
		/// Delete the given DataSource from the database
		/// </summary>
		public virtual void Delete(Model.DataSource dataSource)
		{
			try
			{
				Trace.WriteVerbose("({0})", "Delete", CLASSNAME, dataSource.ToString());

        var helper = Database.GetDbHelper();
				helper.ExecuteSPNonQuery(_storedProcedure_Delete,
					helper.CreateInputParam("@Id", dataSource.Id));
			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", "Delete", CLASSNAME, ex, dataSource.ToString());
				throw DbHelper.TranslateException(ex);
			}
		}

    /// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_Delete = "[AS].[DataSourcesGennie_Delete]";



		/// <summary>
		/// Modify the given DataSource in the database
		/// </summary>
		public virtual void Modify(Model.DataSource modifiedDataSource)
		{
			try
			{
				Trace.WriteVerbose("({0})", "Modify", CLASSNAME, modifiedDataSource.ToString());

				var helper = Database.GetDbHelper();
        int recordsAffected = helper.ExecuteSPNonQuery(_storedProcedure_Modify,
					helper.CreateInputParam("@Id", modifiedDataSource.Id),
					helper.CreateInputParam("@ListName", modifiedDataSource.ListName),
					helper.CreateInputParam("@Object_Id", modifiedDataSource.Object_Id),
					helper.CreateInputParam("@Key_Column_Id", modifiedDataSource.Key_Column_Id),
					helper.CreateInputParam("@Value_Column_Id", modifiedDataSource.Value_Column_Id));

				if (recordsAffected == 0)
				{
					throw new DalNothingUpdatedException("No records were updated (Table: DataSources). DataSource=" + modifiedDataSource.ToString());
				}
			}
			catch (Exception ex)
			{
				Trace.WriteError("({0})", "Modify", CLASSNAME, ex, modifiedDataSource.ToString());
				throw DbHelper.TranslateException(ex);
			}
		}
		
            /// <summary>
            /// String containing stored procedure name
            /// </summary>
	    protected string _storedProcedure_Modify = "[AS].[DataSourcesGennie_Modify]";
		
	/// <summary>
	/// Modify only the specified properties of the DataSource 
	/// specified by:
	/// </summary>
		/// <param name="id">PK</param>
	/// <param name="propValues">Properties to update</param>
		public virtual void Modify( Int32 id,  params KeyValuePair<string,object>[] propValues)
		{
			 try
      {
        Trace.WriteVerbose("({0})", "Modify", CLASSNAME, id);
        
        if (propValues.Length == 0)
        {
			Trace.WriteVerbose("No properties to update.", "Modify", CLASSNAME);
			return;
		}
        
        var helper = Database.GetDbHelper();
        StringBuilder sqlStatement =  new StringBuilder("UPDATE [AS].[DataSources] SET ");
        List<DbParameter> parameterList = new List<DbParameter>();
        for (int i = 0; i < propValues.Length ; i++)
        { 
          sqlStatement.AppendFormat( "[{0}]=@{0}", propValues[i].Key);
          if (i< propValues.Length -1)
            sqlStatement.Append( ", ");

          parameterList.Add(helper.CreateInputParam("@" + propValues[i].Key, propValues[i].Value != null ? propValues[i].Value : DBNull.Value));
          
        }
        sqlStatement.Append(" WHERE ");
         sqlStatement.Append("[Id]=@Id");
			     parameterList.Add( helper.CreateInputParam("@Id", id));
			

              int recordsAffected = helper.ExecuteText(sqlStatement.ToString(),
                                              parameterList.ToArray());
        
        if (recordsAffected == 0)
        {
          throw new DalNothingUpdatedException(string.Format("No records were updated (Table: DataSources). Id={0}", id));
        }

      }
      catch (Exception ex)
      {
        Trace.WriteError("({0})", "Modify", CLASSNAME, ex, id);
        throw DbHelper.TranslateException(ex);
      }

      }



		/// <summary>
		/// Get a DataSource by id from the database
		/// </summary>
		public virtual Model.DataSource GetById(Int32 id)
		{
			DbDataReader reader = null;
			try
			{
        var helper = Database.GetDbHelper();
                
        reader = helper.ExecuteSPReader(_storedProcedure_GetById,
					helper.CreateInputParam("@Id", id));
				
				Model.DataSource result = null;

				if (reader.Read())
          result = CreateDataSource(reader);

				return result;
			}
			catch (Exception ex)
			{
				Trace.WriteError("{0}", "GetById", CLASSNAME, ex, id);
				throw DbHelper.TranslateException(ex);
			}
			finally 
			{
				if (reader != null)
					reader.Close();
			}
		}
		
    /// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_GetById = "[AS].[DataSourcesGennie_GetById]";


		
		/// <summary>
		/// Get all DataSource records from the database
		/// </summary>
		public virtual List<Model.DataSource> GetAll()
		{
			DbDataReader reader = null;
			try
			{
        var helper = Database.GetDbHelper();
        reader = helper.ExecuteSPReader(_storedProcedure_GetAll);
								
				List<Model.DataSource> result = new List<Model.DataSource>();
				while (reader.Read())
				{
				  result.Add(CreateDataSource(reader));
				}
				
				return result;
			}
			catch (Exception ex)
			{
				Trace.WriteError("()", "GetAll", CLASSNAME, ex);
				throw DbHelper.TranslateException(ex);
			}
			finally 
			{
				if (reader != null)
					reader.Close();
			}
		}
		
		/// <summary>
    /// String containing stored procedure name
    /// </summary>
		protected string _storedProcedure_GetAll = "[AS].[DataSourcesGennie_GetAll]";
		
		
		
		/// <summary>
		/// Create a Model.DataSource
		/// </summary>
		protected virtual Model.DataSource CreateDataSource(DbDataReader reader)
		{
			try
			{	
        Model.DataSource result = new Model.DataSource(
          (Int32)reader["Id"], 
          (String)reader["ListName"], 
          (Int32)reader["Object_Id"], 
          (Int32)reader["Key_Column_Id"], 
          (Int32)reader["Value_Column_Id"]
						);
				return result;
			}
			catch (Exception ex)
			{
				Trace.WriteError("", "CreateDataSource", CLASSNAME, ex);
				throw DbHelper.TranslateException(ex);
			}
		}	
	}
}